### PR TITLE
Update to Envoy v1.14.4

### PR DESCRIPTION
**Pull request by mmanciop**
* Update to latest Envoy container
* Use Docker multistep build to avoid tainting the Envoy container
* Override container's `/etc/envoy/envoy.yaml` rather than changing the container's `ENTRYPOINT`
* Update tracing configs

### CODE REVIEW

**Comment by sriemer** [comment]
Thanks, Michele. Will check.
What I'd really like to see would be that we would rename "LIBC_VERSION" to "LIBC_FLAVOR" to be more precise.

**Comment by sriemer** [comment]
Configuration in `.env` now needs `download_key=...` to be set. Needs to be part of the README.

**Comment by sriemer** [comment]
Need to log in to `containers.instana.io` first before being able to pull the image.

**Comment by sriemer** [comment]
The envoy process does not load our tracer although it is there.
```
envoy_1       | [2020-08-04 16:11:05.115][1][info][config] [source/server/configuration_impl.cc:103] loading tracing configuration
envoy_1       | [2020-08-04 16:11:05.115][1][info][config] [source/server/configuration_impl.cc:114]   validating default server-wide tracing driver: envoy.tracers.dynamic_ot
```
Might be possible that they're using the OpenTracing 1.6.0 API now.
See: https://github.com/instana/cpp-sensor/pull/32
Will check tomorrow.

**Comment by mmanciop** [comment]
> Need to log in to `containers.instana.io` first before being able to pull the image.

Done

**Comment by mmanciop** [comment]
Okay, I fixed what I could fix, the rest of the fun with OpenTracing is for you @sriemer :D

**Pull request closed without merging**
